### ISSUE TITLE
As a user, I can add line items to invoices

### ISSUE THREAD

**Issue by sininoble** [EdgarBarrientos/Invoicify#6]
As a user, I would like to add line items to invoices, 
so that  I can update line items with invoices.

Details:
Every invoice has a list of items. Each one is unique and contains a description, quantity and fee. Item fees come in 2 different types: Flat fee and Rate based fee.

Rate based fees:
- have a rate
- have a quantity
- can calculate the total fee

Flat fees:
- have an amount
- can calculate the total fee

Acceptance Criteria: 
- [x] Goal is that if you have Item description "Dev Work" multiple times, you have multiple line items. They aren't "squashed". They are their own instance.
- [x] Items have 3 properties: description, quantity and the total fees
- [x] There are 2 types of fees: flat fees and rate-based fees
- [x] Fee is the total cost of each flat fee item or total cost of rate based items.

**Comment by ranga608667** [comment]
[
![Entities for Invoice, items](https://user-images.githubusercontent.com/82679923/125144983-5a2d8f80-e0e5-11eb-8353-9be4403465b1.PNG)
](url)

**Comment by ranga608667** [comment]
Entity details attached.
![Entities for Invoice, items](https://user-images.githubusercontent.com/82679923/125145641-a679cf00-e0e7-11eb-94bf-c9a5b7bc8222.PNG)

**Comment by sininoble** [comment]
Wes clarified the requirements with the team.  Ranga will be updating the updated entity design document.
